- generic [active] [ref=e1]:
  - generic [ref=e2]:
    - banner [ref=e15]:
      - generic [ref=e17]:
        - generic [ref=e18]:
          - generic [ref=e19]:
            - img [ref=e20]
            - heading "Pertunjukan Wayang Orang Sriwedari - Rama Tambak" [level=1] [ref=e23]
          - paragraph [ref=e24]: "Staff: Ibe"
        - generic [ref=e25]:
          - button "Refresh" [ref=e26]:
            - img [ref=e27]
          - link "Pengaturan" [ref=e32] [cursor=pointer]:
            - /url: /organizer/events/12bde9e9-96d0-40da-ac2d-20a9e2768ec8/gate
            - img [ref=e33]
          - button "Logout" [ref=e36]:
            - img [ref=e37]
    - main [ref=e40]:
      - generic [ref=e41]:
        - generic [ref=e42]:
          - article [ref=e43]:
            - paragraph [ref=e44]: Total tiket
            - paragraph [ref=e45]: "5"
          - article [ref=e46]:
            - paragraph [ref=e47]: Checked in
            - paragraph [ref=e48]: "2"
          - article [ref=e49]:
            - paragraph [ref=e50]: Belum masuk
            - paragraph [ref=e51]: "3"
        - generic [ref=e52]:
          - generic [ref=e53]:
            - img [ref=e54]
            - text: Check-in progress
          - generic [ref=e59]: 40%
      - generic [ref=e62]:
        - generic [ref=e63]:
          - generic [ref=e64]:
            - button "Suara aktif" [ref=e66]:
              - img [ref=e67]
            - button "Mulai Scan" [ref=e71]:
              - img [ref=e72]
              - text: Mulai Scan
          - generic [ref=e76]:
            - img [ref=e78]
            - paragraph [ref=e81]: Kamera tidak aktif
            - paragraph [ref=e82]: Klik "Mulai Scan" untuk mengaktifkan kamera
        - generic [ref=e87]: atau
        - generic [ref=e88]:
          - generic [ref=e89]:
            - img [ref=e90]
            - generic [ref=e92]: Input Manual
          - textbox "Masukkan kode tiket..." [ref=e93]
          - button "Check In" [disabled] [ref=e94]:
            - img [ref=e115]
            - text: Check In
        - generic [ref=e118]:
          - generic [ref=e119]:
            - img [ref=e120]
            - generic [ref=e122]:
              - heading "Sudah Check-in" [level=3] [ref=e123]
              - paragraph [ref=e124]: Tiket sudah di-check-in
          - paragraph [ref=e125]: "Check-in pada: 8/4/2026, 18.37.46"
  - button "Open Next.js Dev Tools" [ref=e10] [cursor=pointer]:
    - img [ref=e11]
  - alert [ref=e14]